name: ai_routine_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.11.0
dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.6.0  # للاتصال بقاعدة البيانات والمصادقة
  google_generative_ai: ^0.4.0 # للتعامل مع Gemini
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  path: ^1.9.0
  flutter_local_notifications: ^17.1.0
  timezone: ^0.9.2
  flutter_timezone: ^3.0.1
  uuid: ^4.3.3          # لتوليد معرفات فريدة محلياً قبل المزامنة
  intl: ^0.19.0         # لتنسيق التواريخ
  shared_preferences: ^2.2.2 # لتخزين إعدادات بسيطة (مثل الثيم)
  lottie: ^3.1.0        # للرسوم المتحركة
  google_fonts: ^6.1.0  # للخطوط الجميلة
  flutter_dotenv: ^6.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env    # أضف هذا السطر هنا